#define SHORT_THROW_POINT_CLOUD_FRAME_TOPIC "hololensShortThrowPointCloudFrame"
#define LONG_THROW_POINT_CLOUD_FRAME_TOPIC "hololensLongThrowPointCloudFrame"

#define OCTOMAP_CURRENT_FRAME_TOPIC "octomapCurrentFrame"
#define OCTOMAP_STATIC_OBJECTS_TOPIC "octomapStaticObjects"
#define OCTOMAP_DYNAMIC_OBJECTS_TOPIC "octomapDynamicObjects"
#define OCTOMAP_DYNAMIC_OBJECTS_CLUSTERS_TOPIC "octomapDynamicObjectClusters"

#define BOUNDING_BOX_DYNAMIC_OBJECT_CLUSTERS_TOPIC "boundingBoxDynamicObjectClusters"

#define DYNAMIC_CLUSTER_CENTROIDS_ALL_TOPIC "dynamicClusterCentroidsAll"
#define DYNAMIC_CLUSTER_CENTROIDS_CLUSTERS_OF_INTEREST_TOPIC "dynamicClusterCentroidsClustersOfInterest"
#define DYNAMIC_CLUSTER_CENTROIDS_HUMAN_TOPIC "dynamicClusterCentroidsHuman"
#define DYNAMIC_CLUSTER_CENTROIDS_ROBOT_TOPIC "dynamicClusterCentroidsRobot"
#define DYNAMIC_CLUSTER_CENTROIDS_UNKNOWN_TOPIC "dynamicClusterCentroidsUnknown"

#define CLUSTER_CLASSIFICATION_SERVICE_NAME "clustersClassifier/classifyClusters"

#define ENABLE_SPATIAL_MAP_UPDATES_TOPIC "enableSpatialMapUpdates"
#define CLEAR_SPATIAL_MAP_TOPIC "clearSpatialMap"