#define SHORT_THROW_POINT_CLOUD_FRAME_TOPIC "hololensShortThrowPointCloudFrame"
#define LONG_THROW_POINT_CLOUD_FRAME_TOPIC "hololensLongThrowPointCloudFrame"

#define OCTOMAP_CURRENT_FRAME_TOPIC "octomapCurrentFrame"
#define OCTOMAP_STATIC_OBJECTS_TOPIC "octomapStaticObjects"
#define OCTOMAP_DYNAMIC_OBJECTS_TOPIC "octomapDynamicObjects"
#define OCTOMAP_DYNAMIC_OBJECTS_CLUSTERS_TOPIC "octomapDynamicObjectClusters"