#!/usr/bin/env python

import sys

from hololens_point_cloud_control_gui.control_gui import ControlGuiPlugin
from rqt_gui.main import Main

plugin = 'hololens_point_cloud_control_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
