# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#    Configuration file containing the default parameters for the octomap based spatial mapper.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Hyper parameters for insertion of point clouds into the octree data structure.
octomapLeafSize: 0.05
octreeInsertionLazyEval: false
octreeInsertionDiscretize: false

# Switches and hyper parameters for octree freespace filtering.
doOctreeFreespaceFiltering: true
octreeFilteringRelativeNeighborDistance: 1.5

# Hyper parameters for incorporating new octrees to the global spatial map.
numFreeObservationsBeforeVoxelRemoval: 5
numFramesBeforePossibleDynamicVoxelRemoval: 10

# Hyper parameters for floor removal in voxels of dynamic objects.
doFloorRemovalInDynamicVoxels: true
floorRemovalMinFloorVoxels: 400 # With a leaf size of 5 cm a face of each voxel spans an area of 25 cm² (or 0.0025 m²). Assuming that the floor is completely flat, a minimum amount of floor voxels of 400 means that we must find at least 1 m² of potential floor in order for the voxels to be considered the new floor height.
floorRemovalRelativeNoiseHeight: 1

# Hyper parameters for clustering dynamic voxels.
voxelClusteringRelativeClusterDistance: 1.9
voxelClusteringMinClusterSize: 8  # With a leaf size of 5 cm each voxel holds a volume of 125 cm³. A minimum cluster size of 8 results in a removal of all clusters smaller than 1000cm³ (or 1 liter).

# Switches and hyper parameters for removal of dynamic voxel clusters containing only sensor noise.
doNoiseClusterRemoval: true
noiseClusterRemovalRelativeNeighborDistance: 1.0
noiseClusterRemovalStaticNeighborPercentage: 0.75

# Hyper parameters for tracking objects.
trackingStdLimit: 1.0
trackingConstantVelocityNoiseX: 1.4
trackingConstantVelocityNoiseY: 1.4
trackingNoiseParamsX: 0.1
trackingNoiseParamsY: 0.1
trackingSequenceSize: 4
trackingSequenceTime: 0.3
