# This object tracker tracks all clusters.
clustersTrackerAll:
    filter_type: "UKF"                           # The Kalman filter type: EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
    cv_noise_params:                             # The noise for the constant velocity prediction model
        x: 1.4
        y: 1.4
        std_limit: 1.0                           # upper limit for the standard deviation of the estimated position 
    detectors:                                   # Add detectors under this namespace
        octomap_based_spatial_mapper:            # Name of detector (used internally to identify them). Has to be unique.
            topic: "/dynamicClusterCentroidsAll" # The topic on which the geometry_msgs/PoseArray is published
            observation_model: "CARTESIAN"       # Observation model: CARTESIAN or POLAR
            noise_params:                        # The noise for the cartesian or polar observation model
                x: 0.1
                y: 0.1
            matching_algorithm: "NN"             # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
            seq_size: 4                          # Minimum number of observations for new track creation
            seq_time: 0.3                        # Minimum interval between observations for new track creation

# This object tracker tracks only clusters classified as being a human.
clustersTrackerHuman:
    filter_type: "UKF"
    cv_noise_params:
        x: 1.4
        y: 1.4
        std_limit: 1.0
    detectors:
        octomap_based_spatial_mapper:
            topic: "/dynamicClusterCentroidsHuman"
            observation_model: "CARTESIAN"
            noise_params:
                x: 0.1
                y: 0.1
            matching_algorithm: "NN"
            seq_size: 4
            seq_time: 0.3

# This object tracker tracks only clusters classified as being an object corresponding to the unknown/background class.
clustersTrackerUnknown:
    filter_type: "UKF"
    cv_noise_params:
        x: 1.4
        y: 1.4
        std_limit: 1.0
    detectors:
        octomap_based_spatial_mapper:
            topic: "/dynamicClusterCentroidsUnknown"
            observation_model: "CARTESIAN"
            noise_params:
                x: 0.1
                y: 0.1
            matching_algorithm: "NN"
            seq_size: 4
            seq_time: 0.3
