#pragma once

#define SHORT_THROW_PIXEL_DIRECTIONS_TOPIC "/hololensShortThrowPixelDirections"
#define LONG_THROW_PIXEL_DIRECTIONS_TOPIC "/hololensLongThrowPixelDirections"

#define SHORT_THROW_DEPTH_TOPIC "/hololensShortThrowDepth"
#define LONG_THROW_DEPTH_TOPIC "/hololensLongThrowDepth"

#define SHORT_THROW_IMAGE_TOPIC "hololensShortThrowImage"
#define LONG_THROW_IMAGE_TOPIC "hololensLongThrowImage"

#define SHORT_THROW_POINT_CLOUD_CAM_SPACE_UNFILTERED_TOPIC "hololensShortThrowPointCloudCamSpaceUnfiltered"
#define LONG_THROW_POINT_CLOUD_CAM_SPACE_UNFILTERED_TOPIC "hololensLongThrowPointCloudCamSpaceUnfiltered"

#define SHORT_THROW_POINT_CLOUD_CAM_SPACE_TOPIC "hololensShortThrowPointCloudCamSpace"
#define LONG_THROW_POINT_CLOUD_CAM_SPACE_TOPIC "hololensLongThrowPointCloudCamSpace"

#define SHORT_THROW_POINT_CLOUD_WORLD_SPACE_TOPIC "hololensShortThrowPointCloudWorldSpace"
#define LONG_THROW_POINT_CLOUD_WORLD_SPACE_TOPIC "hololensLongThrowPointCloudWorldSpace"

#define SHORT_THROW_ARTIFICIAL_ENDPOINTS_CAM_SPACE_TOPIC "hololensShortThrowArtificialEndpointsCamSpace"
#define LONG_THROW_ARTIFICIAL_ENDPOINTS_CAM_SPACE_TOPIC "hololensLongThrowArtificialEndpointsCamSpace"

#define SHORT_THROW_ARTIFICIAL_ENDPOINTS_WORLD_SPACE_TOPIC "hololensShortThrowArtificialEndpointsWorldSpace"
#define LONG_THROW_ARTIFICIAL_ENDPOINTS_WORLD_SPACE_TOPIC "hololensLongThrowArtificialEndpointsWorldSpace"

#define HOLOLENS_POSITION_TOPIC "hololensPosition"

#define SHORT_THROW_POINT_CLOUD_FRAME_TOPIC "hololensShortThrowPointCloudFrame"
#define LONG_THROW_POINT_CLOUD_FRAME_TOPIC "hololensLongThrowPointCloudFrame"
