# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#    Default configuration file for the stereo image receiver.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Camera intrinsics of the stereo cameras.
stereoCamCalibrationFilePath: $(find hololens_stereo_image_receiver)/config/stereo_cam_calibration.yml

# Parameters for preprocessing the raw stereo images.
preprocessingDoImageNormalization: false
preprocessingDoHistogramEqualization: false
preprocessingDoMedianFiltering: false
preprocessingMedianFilterKernelSize: 3

# Parameters for OpenCV's StereoSGBM algorithm.
sgbmMinDisparity: 0
sgbmNumDisparities: 96
sgbmBlockSize: 15
sgbmP1Multiplier: 8
sgbmP2Multiplier: 32
sgbmDisp12MaxDiff: 100
sgbmPreFilterCap: 0
sgbmUniquenessRatio: 15
sgbmSpeckleWindowSize: 200
sgbmSpeckleRange: 2
sgbmMode: 1 # 0 = MODE_SGBM, 1 = MODE_HH, 2 = MODE_SGBM_3WAY, 3 = MODE_HH4

# Parameters for OpenCV's DisparityWLSFilter.
wlsLambda: 10000.0
wlsSigma: 1.0

# Parameters for the disparity map visualization.
dispVisMultiplier: 2.0

# Parameters for point cloud reconstruction.
reconstructPointCloudFromRawDisparityMap: false
minDisparityForReconstruction: 5.0

# Parameters for point cloud downsampling.
doDownsampling: true
downsamplingLeafSize: 0.01

# Parameters for point cloud outlier removal using a radius outlier removal filter.
doOutlierRemovalRadius: true
outlierRemovalRadiusSearch: 0.05
outlierRemovalMinNeighborsInRadius: 12

# Parameters for point cloud outlier removal using a statistical outlier removal filter.
doOutlierRemovalStatistical: false
outlierRemovalNeighborsToCheck: 10
outlierRemovalStdDeviationMultiplier: 0.5

# Parameters for point cloud outlier removal using euclidean clustering.
doOutlierRemovalClustering: false
outlierRemovalClusterTolerance: 0.08
outlierRemovalMinClusterSize: 500
