#!/usr/bin/env python

import sys

from octomap_based_spatial_mapper_control_gui.control_gui import ControlGuiPlugin
from rqt_gui.main import Main

plugin = 'control_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
